@php $editing = isset($openingBalance); $rows = old('lines', $editing ? $openingBalance->lines->toArray() : [['debit'=>'0.0000','credit'=>'0.0000'],['debit'=>'0.0000','credit'=>'0.0000']]); @endphp
@if($errors->any())<div class="alert alert-danger dg-alert"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@csrf
@if($editing) @method('PUT') @else <input type="hidden" name="request_key" value="{{ old('request_key', (string) Illuminate\Support\Str::uuid()) }}"> @endif
<section class="dg-section"><article class="card dg-card"><header class="card-header dg-card-header"><h2 class="h6 mb-0">Opening Balance Information</h2></header><div class="card-body dg-card-body"><div class="row g-3">
<div class="col-md-3"><label class="dg-label" for="financial_year_id">Financial Year</label><select class="form-select dg-select" id="financial_year_id" name="financial_year_id" required>@foreach($financialYears as $fy)<option value="{{ $fy->id }}" @selected(old('financial_year_id',$openingBalance->financial_year_id ?? null)==$fy->id)>{{ $fy->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="dg-label" for="business_date">Business Date</label><input class="form-control dg-input" type="date" id="business_date" name="business_date" value="{{ old('business_date',isset($openingBalance)?$openingBalance->business_date->format('Y-m-d'):'') }}" required></div>
@include('company.components.nepali-date-field', ['adInputId' => 'business_date', 'adDate' => old('business_date', $openingBalance->business_date ?? null), 'columnClass' => 'col-md-3'])
<div class="col-md-3"><label class="dg-label" for="type">Type</label><select class="form-select dg-select" id="type" name="type">@foreach(\App\Models\OpeningBalance::TYPES as $type)<option value="{{ $type }}" @selected(old('type',$openingBalance->type ?? '')===$type)>{{ ucwords(str_replace('_',' ',$type)) }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="dg-label" for="reference_number">Reference</label><input class="form-control dg-input" id="reference_number" name="reference_number" value="{{ old('reference_number',$openingBalance->reference_number ?? '') }}" required></div>
<div class="col-12"><label class="dg-label" for="remarks">Remarks</label><textarea class="form-control dg-input" id="remarks" name="remarks">{{ old('remarks',$openingBalance->remarks ?? '') }}</textarea></div>
</div></div></article></section>
<section class="dg-section"><article class="card dg-card"><header class="card-header dg-card-header d-flex justify-content-between"><h2 class="h6 mb-0">Debit and Credit Lines</h2><button type="button" class="btn btn-sm btn-outline-success dg-btn" id="dg-ob-add-line">Add Line</button></header><div class="table-responsive"><table class="table dg-table mb-0"><thead><tr><th>Chart Account</th><th>Customer/Supplier</th><th>Operational Account</th><th>Debit</th><th>Credit</th><th>Description</th><th></th></tr></thead><tbody id="dg-ob-lines">
@foreach($rows as $i=>$row)<tr><td><select class="form-select dg-select" name="lines[{{ $i }}][chart_account_id]" required><option value="">Select</option>@foreach($chartAccounts as $account)<option value="{{ $account->id }}" @selected(($row['chart_account_id']??null)==$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></td>
<td><select class="form-select dg-select" name="lines[{{ $i }}][subledger_type]"><option value="">None</option><option value="customer" @selected(($row['subledger_type']??'')==='customer')>Customer</option><option value="supplier" @selected(($row['subledger_type']??'')==='supplier')>Supplier</option></select><input class="form-control dg-input mt-1" type="number" min="1" name="lines[{{ $i }}][subledger_id]" value="{{ $row['subledger_id']??'' }}" placeholder="Customer/Supplier ID"></td>
<td><select class="form-select dg-select" name="lines[{{ $i }}][operational_account_id]"><option value="">None</option>@foreach($operationalAccounts as $op)<option value="{{ $op->id }}" @selected(($row['operational_account_id']??null)==$op->id)>{{ $op->account_name }}</option>@endforeach</select></td>
<td><input class="form-control dg-input dg-ob-debit" type="number" min="0" step="0.0001" name="lines[{{ $i }}][debit]" value="{{ $row['debit']??'0.0000' }}"></td><td><input class="form-control dg-input dg-ob-credit" type="number" min="0" step="0.0001" name="lines[{{ $i }}][credit]" value="{{ $row['credit']??'0.0000' }}"></td><td><input class="form-control dg-input" name="lines[{{ $i }}][description]" value="{{ $row['description']??'' }}"></td><td><button type="button" class="btn btn-sm btn-outline-danger dg-btn dg-ob-remove">×</button></td></tr>@endforeach
</tbody><tfoot><tr><th colspan="3">Posting Preview</th><th id="dg-ob-debit-total">0.0000</th><th id="dg-ob-credit-total">0.0000</th><th>Difference: <span id="dg-ob-difference">0.0000</span></th><th></th></tr></tfoot></table></div></article></section>
<button class="btn btn-primary dg-btn" type="submit">Save Draft</button>
<script>
document.addEventListener('DOMContentLoaded',()=>{const body=document.getElementById('dg-ob-lines');const recalc=()=>{let d=0,c=0;body.querySelectorAll('.dg-ob-debit').forEach(x=>d+=Number(x.value||0));body.querySelectorAll('.dg-ob-credit').forEach(x=>c+=Number(x.value||0));document.getElementById('dg-ob-debit-total').textContent=d.toFixed(4);document.getElementById('dg-ob-credit-total').textContent=c.toFixed(4);document.getElementById('dg-ob-difference').textContent=(d-c).toFixed(4)};body.addEventListener('input',recalc);body.addEventListener('click',e=>{if(e.target.classList.contains('dg-ob-remove')&&body.rows.length>2){e.target.closest('tr').remove();recalc()}});document.getElementById('dg-ob-add-line').addEventListener('click',()=>{const row=body.rows[0].cloneNode(true),i=body.rows.length;row.querySelectorAll('input,select').forEach(x=>{x.name=x.name.replace(/lines\[\d+\]/,`lines[${i}]`);if(x.tagName==='INPUT')x.value=x.classList.contains('dg-ob-debit')||x.classList.contains('dg-ob-credit')?'0.0000':'';else x.selectedIndex=0});body.appendChild(row);recalc()});recalc()});
</script>
