@extends('company.layout')
@section('title', 'General Ledger')
@section('content')
<div class="dg-page"><main class="dg-container"><div class="container-fluid">
<h1 class="dg-page-title">General Ledger</h1>
<form method="GET" class="card dg-card card-body row g-2 align-items-end mb-3"><div class="col-md-2"><label>Financial Year</label><select name="financial_year_id" class="form-select">@foreach($financialYears as $fy)<option value="{{ $fy->id }}" @selected($fy->id===$financialYear->id)>{{ $fy->name }}</option>@endforeach</select></div><div class="col-md-3"><label>Chart Account</label><select name="chart_account_id" class="form-select">@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($account->id===$accountId)>{{ $account->code }} — {{ $account->name }}{{ $account->status !== 'active' ? ' (Inactive)' : '' }}</option>@endforeach</select></div><div class="col-md-2"><label>From</label><input type="date" name="from_date" value="{{ $from }}" class="form-control"></div><div class="col-md-2"><label>To</label><input type="date" name="to_date" value="{{ $to }}" class="form-control"></div><div class="col-md-3"><button class="btn btn-primary">Run</button> <button name="print" value="1" class="btn btn-outline-secondary">Print</button></div></form>
<div class="row g-2 mb-3">@foreach(['Opening Balance'=>$report['opening_balance'],'Period Debit'=>$report['period_debit'],'Period Credit'=>$report['period_credit'],'Closing Balance'=>$report['closing_balance']] as $label=>$value)<div class="col-md-3"><div class="card dg-card card-body"><small>{{ $label }}</small><strong class="text-end">{{ number_format((float)$value,2) }}</strong></div></div>@endforeach</div>
<div class="card dg-card table-responsive"><table class="table dg-table mb-0"><thead><tr><th>Date</th><th>Entry</th><th>Reference</th><th>Source</th><th>Description</th><th class="text-end">Debit</th><th class="text-end">Credit</th><th class="text-end">Running</th></tr></thead><tbody>@forelse($report['rows'] as $row)<tr><td>{{ $row['entry_date'] }}</td><td>{{ $row['entry_number'] }}</td><td>{{ $row['reference'] }}</td><td>{{ $row['source'] }}</td><td>{{ $row['description'] }}</td><td class="text-end">{{ number_format((float)$row['debit'],2) }}</td><td class="text-end">{{ number_format((float)$row['credit'],2) }}</td><td class="text-end">{{ number_format((float)$row['running_balance'],2) }}</td></tr>@empty<tr><td colspan="8" class="text-center">No ledger activity.</td></tr>@endforelse</tbody></table></div>
</div></main></div>@if(request('print'))<script>window.print()</script>@endif
@endsection
