@extends('company.layout')
@section('title', 'Profit & Loss')
@section('content')
<div class="dg-page"><main class="dg-container"><div class="container-fluid"><h1 class="dg-page-title">Profit & Loss</h1>
<form method="GET" class="card dg-card card-body row g-2 align-items-end mb-3"><div class="col-md-3"><label>Financial Year</label><select name="financial_year_id" class="form-select">@foreach($financialYears as $fy)<option value="{{ $fy->id }}" @selected($fy->id===$financialYear->id)>{{ $fy->name }}</option>@endforeach</select></div><div class="col-md-2"><label>From</label><input type="date" name="from_date" value="{{ $from }}" class="form-control"></div><div class="col-md-2"><label>To</label><input type="date" name="to_date" value="{{ $to }}" class="form-control"></div><div class="col-md-2 form-check"><input type="checkbox" name="show_zero" value="1" class="form-check-input" @checked($showZero)><label>Show Zero Balance</label></div><div class="col-md-3"><button class="btn btn-primary">Run</button> <button name="print" value="1" class="btn btn-outline-secondary">Print</button></div></form>
<div class="row g-2 mb-3">@foreach(['Income'=>$report['income'],'Expense'=>$report['expense'],$report['result']=>$report['net']] as $label=>$value)<div class="col-md-4"><div class="card dg-card card-body"><small>{{ $label }}</small><strong class="text-end">{{ number_format((float)$value,2) }}</strong></div></div>@endforeach</div>
<div class="card dg-card table-responsive"><table class="table dg-table mb-0"><thead><tr><th>Class</th><th>Code</th><th>Account</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($report['rows'] as $row)<tr><td>{{ ucfirst($row['account']->account_class) }}</td><td>{{ $row['account']->code }}</td><td>{{ $row['account']->name }}{{ $row['account']->status !== 'active' ? ' (Inactive)' : '' }}</td><td class="text-end">{{ number_format((float)$row['amount'],2) }}</td></tr>@empty<tr><td colspan="4" class="text-center">No Profit & Loss activity.</td></tr>@endforelse</tbody></table></div>
</div></main></div>@if(request('print'))<script>window.print()</script>@endif
@endsection
