@extends('company.layout')
@section('title', 'Trial Balance')
@section('content')
<div class="dg-page"><main class="dg-container"><div class="container-fluid"><h1 class="dg-page-title">Trial Balance</h1>
<form method="GET" class="card dg-card card-body row g-2 align-items-end mb-3"><div class="col-md-3"><label>Financial Year</label><select name="financial_year_id" class="form-select">@foreach($financialYears as $fy)<option value="{{ $fy->id }}" @selected($fy->id===$financialYear->id)>{{ $fy->name }}</option>@endforeach</select></div><div class="col-md-2"><label>From</label><input type="date" name="from_date" value="{{ $from }}" class="form-control"></div><div class="col-md-2"><label>To</label><input type="date" name="to_date" value="{{ $to }}" class="form-control"></div><div class="col-md-2 form-check"><input type="checkbox" name="show_zero" value="1" class="form-check-input" @checked($showZero)><label>Show Zero Balance</label></div><div class="col-md-3"><button class="btn btn-primary">Run</button> <button name="print" value="1" class="btn btn-outline-secondary">Print</button></div></form>
@unless($report['integrity'])<div class="alert alert-danger">REPORT INTEGRITY FAILURE — Trial Balance totals do not balance.</div>@endunless
<div class="card dg-card table-responsive"><table class="table dg-table mb-0"><thead><tr><th>Code</th><th>Account</th><th>Opening Dr</th><th>Opening Cr</th><th>Period Dr</th><th>Period Cr</th><th>Closing Dr</th><th>Closing Cr</th></tr></thead><tbody>@foreach($report['rows'] as $row)<tr><td>{{ $row['account']->code }}</td><td>{{ $row['account']->name }}{{ $row['account']->status !== 'active' ? ' (Inactive)' : '' }}</td>@foreach(['opening_debit','opening_credit','period_debit','period_credit','closing_debit','closing_credit'] as $key)<td class="text-end">{{ number_format((float)$row[$key],2) }}</td>@endforeach</tr>@endforeach</tbody><tfoot><tr class="fw-bold"><td colspan="2">TOTAL</td>@foreach(['opening_debit','opening_credit','period_debit','period_credit','closing_debit','closing_credit'] as $key)<td class="text-end">{{ number_format((float)$report['totals'][$key],2) }}</td>@endforeach</tr></tfoot></table></div>
</div></main></div>@if(request('print'))<script>window.print()</script>@endif
@endsection
