@extends('company.layout')
@section('title','Opening Balance '.$openingBalance->reference_number)
@section('content')
@php $u=auth()->user(); @endphp
<div class="dg-page"><header class="dg-toolbar"><div class="container-fluid d-flex justify-content-between"><div><h1 class="h4 mb-0">Opening Balance {{ $openingBalance->reference_number }}</h1><small>{{ ucfirst($openingBalance->status) }} · {{ $openingBalance->is_locked?'Locked':'Unlocked' }}</small></div><nav class="d-flex gap-1"><a class="btn btn-outline-secondary dg-btn" href="{{ route('company.opening-balances.index') }}">Back</a>@if($u->hasPermission('opening-balance.audit-view'))<a class="btn btn-outline-info dg-btn" href="{{ route('company.opening-balances.audit',$openingBalance) }}">Audit</a>@endif @if($u->hasPermission('opening-balance.print'))<a class="btn btn-outline-dark dg-btn" href="{{ route('company.opening-balances.print',$openingBalance) }}">Print</a>@endif</nav></div></header>
<main class="dg-container"><div class="container-fluid">@if(session('success'))<div class="alert alert-success dg-alert">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger dg-alert">{{ session('error') }}</div>@endif
<section class="dg-section"><article class="card dg-card"><div class="card-body dg-card-body"><div class="row"><div class="col-md-3"><b>Financial Year</b><br>{{ $openingBalance->financialYear?->name }}</div><div class="col-md-3"><b>Business Date</b><br>{{ $openingBalance->business_date->format('Y-m-d') }} @include('company.components.nepali-date-display', ['adDate' => $openingBalance->business_date])</div><div class="col-md-3"><b>Type</b><br>{{ ucwords(str_replace('_',' ',$openingBalance->type)) }}</div><div class="col-md-3"><b>Journal / Entry</b><br>{{ $openingBalance->journal?->journal_no ?? 'Not posted' }} / {{ $openingBalance->accountingEntry?->entry_number ?? 'Not posted' }}</div><div class="col-12 mt-2"><b>Remarks</b><br>{{ $openingBalance->remarks ?: '—' }}</div></div></div></article></section>
<section class="dg-section"><article class="card dg-card"><div class="table-responsive"><table class="table dg-table mb-0"><thead><tr><th>#</th><th>Account</th><th>Subledger</th><th>Operational</th><th>Debit</th><th>Credit</th></tr></thead><tbody>@foreach($openingBalance->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ $line->chartAccount->code }} — {{ $line->chartAccount->name }}</td><td>{{ $line->subledger_type ? $line->subledger_type.' #'.$line->subledger_id : '—' }}</td><td>{{ $line->operationalAccount?->account_name ?? '—' }}</td><td>{{ number_format((float)$line->debit,4) }}</td><td>{{ number_format((float)$line->credit,4) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="4">Total</th><th>{{ number_format((float)$openingBalance->lines->sum('debit'),4) }}</th><th>{{ number_format((float)$openingBalance->lines->sum('credit'),4) }}</th></tr></tfoot></table></div></article></section>
<section class="dg-section"><div class="d-flex flex-wrap gap-2">
@if($openingBalance->status==='draft'&&!$openingBalance->is_locked&&$u->hasPermission('opening-balance.edit-draft'))<a class="btn btn-primary dg-btn" href="{{ route('company.opening-balances.edit',$openingBalance) }}">Edit Draft</a>@endif
@foreach(['submit','post'] as $action)@php $expected=['submit'=>'draft','post'=>'approved'][$action]; @endphp @if($openingBalance->status===$expected&&!$openingBalance->is_locked&&$u->hasPermission('opening-balance.'.$action))<form method="POST" action="{{ route('company.opening-balances.'.$action,$openingBalance) }}">@csrf<button class="btn btn-success dg-btn">{{ ucfirst($action) }}</button></form>@endif @endforeach
@if($openingBalance->status==='submitted'&&!$openingBalance->is_locked&&(int)$u->id!==(int)$openingBalance->created_by&&$u->hasPermission('opening-balance.approve'))<form method="POST" action="{{ route('company.opening-balances.approve',$openingBalance) }}">@csrf<button class="btn btn-success dg-btn">Approve</button></form>@endif
@if(in_array($openingBalance->status,['draft','submitted','approved'])&&$u->hasPermission('opening-balance.cancel'))<form class="d-flex gap-1" method="POST" action="{{ route('company.opening-balances.cancel',$openingBalance) }}">@csrf<input class="form-control dg-input" name="reason" required placeholder="Cancellation reason"><button class="btn btn-danger dg-btn">Cancel</button></form>@endif
@if($openingBalance->status==='posted'&&!$openingBalance->is_locked&&$u->hasPermission('opening-balance.reverse'))<form class="d-flex gap-1" method="POST" action="{{ route('company.opening-balances.reverse',$openingBalance) }}">@csrf<input class="form-control dg-input" name="reason" required placeholder="Reversal reason"><button class="btn btn-danger dg-btn">Reverse</button></form>@endif
@if(!$openingBalance->is_locked&&$u->hasPermission('opening-balance.lock'))<form class="d-flex gap-1" method="POST" action="{{ route('company.opening-balances.lock',$openingBalance) }}">@csrf<input class="form-control dg-input" name="reason" required placeholder="Lock reason"><button class="btn btn-warning dg-btn">Lock</button></form>@elseif($openingBalance->is_locked&&$u->hasPermission('opening-balance.unlock'))<form class="d-flex gap-1" method="POST" action="{{ route('company.opening-balances.unlock',$openingBalance) }}">@csrf<input class="form-control dg-input" name="reason" required placeholder="Unlock reason"><button class="btn btn-warning dg-btn">Unlock</button></form>@endif
</div></section></div></main></div>
@endsection
